# Server
server.port=8083
spring.application.name=ms-alertas

# Oracle Database
spring.datasource.url=${DB_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
spring.datasource.username=${DB_USER:hospital_user}
spring.datasource.password=${DB_PASS:hospital123}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format_sql=true

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:hospital}
spring.rabbitmq.password=${RABBITMQ_PASS:hospital123}

hospital.rabbit.alertas-exchange=${HOSPITAL_ALERTAS_EXCHANGE:hospital.alertas.exchange}
hospital.rabbit.alertas-db-queue=${HOSPITAL_ALERTAS_DB_QUEUE:hospital.alertas.db.queue}
