server.port=8085
spring.application.name=ms-productor-signos
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092,localhost:9093,localhost:9094}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
hospital.kafka.topic-signos=${KAFKA_TOPIC_SIGNOS:senales_vitales}
hospital.signos.fixed-rate-ms=${SIGNOS_FIXED_RATE_MS:1000}
hospital.signos.pacientes=${PACIENTE_IDS:1,2,3}
hospital.signos.anomalia-cada=${ANOMALIA_CADA:5}
management.endpoints.web.exposure.include=health,info
